services:
  cassandra:
    image: cassandra:4
    ports:
      - 9042:9042
    volumes:
      - ./resources:/resources
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS=true
